### ISSUE TITLE
Date alias for last successful action run

### ISSUE THREAD

**Issue by zekez** [Yelp/Tron#122]
It would be nice if in addition to

```
shortdate
year
month
day
```

we could have another alias, along the lines of

```
lastdate
```

which would be the equivalent of `shortdate` except that instead of returning the current date, would return the date of the last successful run of the batch. In the event of the batch never having run before a sane default might be to simply return `shortdate`.

The primary motivation is a job like this:

``` yaml
- !Job
    name: log_processing
    schedule: !DailyScheduler
        start_time: "01:00:00"
    actions:
        - &aggregate_logs !Action
            name: aggregate_logs
            command: >
                %(PYTHON)s -m log_aggregator \
                    --date=%(shortdate-1)s
        - &do_stuff_with_logs !Action
            name: do_stuff_with_logs
            command: >
                %(PYTHON)s -m doer_of_stuff \
                    --min-date='7 days ago'
            requires: [*aggregate_logs]
```

The `do_stuff_with_logs` is examining the last 7 days only to fill in holes where `aggregate_logs` failed. In most cases this is causing `do_stuff_with_logs` to do extra unnecessary work. 

Instead it would be nice if we could tell when the last successful run of the `do_stuff_with_logs` action was, and only examine the dates after that.

``` yaml
        - &do_stuff_with_logs !Action
            name: do_stuff_with_logs
            command: >
                %(PYTHON)s -m doer_of_stuff \
                    --min-date=%(lastdate)s
            requires: [*aggregate_logs]
```

From the example above, even the `aggregate_logs` action could make use of this

``` yaml
        - &aggregate_logs !Action
            name: aggregate_logs
            command: >
                %(PYTHON)s -m log_aggregator \
                    --min-date=%(lastdate-1)s
```

guaranteeing that if this batch failed and someone somehow forgot to manually re-run it for the missing day it would still get automatically filled in at the next scheduled run.
