### ISSUE TITLE
support ec2 tag names for node_pool

### ISSUE THREAD

**Issue by koblas** [Yelp/Tron#233]
It would be really handy to have boto support such that one could something like:

```
ec2:
   api_secret: XYZZY
   api_public: QWERTY
   region: us-east-1

ec2_pool:
    - name: api
      tag: production.api
      region: [if not default]
```

Which would in turn do a AWS EC2 lookup on all nodes tagged "production.api"  and make those available as a node pool.  At the moment I'm currently manually configuring the internal IPs of those nodes and fixing up when they change.
