### ISSUE TITLE
Dependent actions do not run if dependency was skipped before the job starts

### ISSUE THREAD

**Issue by kesre** [Yelp/Tron#300]
Repro:
  1. Create a regularly scheduled job with a dependency
```
  - name: "test"
    node: ...
    schedule:
        start_time: "00:01:00"
    actions:
        - name: "foo"
          command: "echo foo"
        - name: "bar"
          command: "echo bar"
          requires: [foo]
```
 2. Skip foo while foo and bar are in state 'scheduled'
 3. Wait for scheduled time

Expected:
    - action "bar" is started at the job's scheduled time (state starting/running/succeeded by the time it is observed)
    - job state is 'running'

Observed:
    - action "bar" is in state 'queued'
    - job state is 'unknown'
