### ISSUE TITLE
Failed first action of two-action job stops scheduler

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#77]
This job makes the scheduler stop pulling from the queue:

```
--- !TronConfiguration

ssh_options: !SSHOptions
  agent: true

nodes:
  - &local
      hostname: 'localhost'
jobs:
  - &random_job
    name: "random_failure_job"
    node: *local
    queueing: true
    schedule: "interval 1 seconds"
    actions:
      - &fa
        name: "fa"
        command: "failing command"
      - &sa
        name: "sa"
        command: "succeeding command"
        requires: [*fa]
```

This is Very Bad.
