### ISSUE TITLE
Add 'owner' field to jobs

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#99]
Sometimes the people who noticed job failures are not the people who maintain the jobs. One solution is to add an `owner` field to each job. Like so:

```
owner: require # one of {require, warn, ignore}
job:
  - name: my_sweet_job
    owner: sjohnson@yelp.com
```

```
tronctl owner my_sweet_job
> mailto:sjohnson@yelp.com # this can be command-clicked in iTerm2, which is nice
```
